# Generated by Django 3.1.2 on 2020-10-22 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skboxing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pas2',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
